# https://taskfile.dev

version: "3"

tasks:
  build-img-v:
    cmds:
      - git pull
      - ./img-gen-v.sh

  compile-kpatch:
    dir: kpatch
    cmds:
      - make clean all
      - mv kpatch ../files/p3/system/